language: php

php:
- 7.0

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer install --prefer-source --no-interaction --ignore-platform-reqs
  - vendor/bin/install-phalcon.sh 3.0.x

script:
  - vendor/bin/phpunit tests/

notifications:
  email: false
